import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MusicMLGeneratedModule, MusicMLGeneratedSharedModule } from './generated/module.js';
import {MusicMLValidator, registerValidationChecks} from './musicml-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MusicMLAddedServices = {
    validation: {
        MusicMLValidator: MusicMLValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MusicMLServices = LangiumServices & MusicMLAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MusicmlModule: Module<MusicMLServices, PartialLangiumServices & MusicMLAddedServices> = {
    validation: {
        MusicMLValidator: () => new MusicMLValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMusicMLServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MusicML: MusicMLServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MusicMLGeneratedSharedModule
    );
    const MidiDsl = inject(
        createDefaultModule({ shared }),
        MusicMLGeneratedModule,
        MusicmlModule
    );
    shared.ServiceRegistry.register(MidiDsl);
    registerValidationChecks(MidiDsl);
    return { shared, MusicML: MidiDsl };
}
