import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MidiDslGeneratedModule, MidiDslGeneratedSharedModule } from './generated/module.js';
import { MidiDslValidator, registerValidationChecks } from './midi-dsl-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MidiDslAddedServices = {
    validation: {
        MidiDslValidator: MidiDslValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MidiDslServices = LangiumServices & MidiDslAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MidiDslModule: Module<MidiDslServices, PartialLangiumServices & MidiDslAddedServices> = {
    validation: {
        MidiDslValidator: () => new MidiDslValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMidiDslServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MidiDsl: MidiDslServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MidiDslGeneratedSharedModule
    );
    const MidiDsl = inject(
        createDefaultModule({ shared }),
        MidiDslGeneratedModule,
        MidiDslModule
    );
    shared.ServiceRegistry.register(MidiDsl);
    registerValidationChecks(MidiDsl);
    return { shared, MidiDsl };
}
